import Image from 'next/image'
import { Reveal } from '@/components/motion/Reveal'
import { differentials } from '@/data/content'
import { media } from '@/data/media'
import { withBasePath } from '@/lib/paths'

export function ExpertiseMethod() {
  return <><section className="section-space expertise-section"><div className="container"><div className="row g-5 align-items-center"><div className="col-lg-6"><Reveal><p className="eyebrow brown">04 · ESPECIALISTA EM MAQUIAGEM</p><h2>Beleza não é fórmula.<br/><em>É individualidade.</em></h2><p className="lead-serif">Cada rosto possui proporções, linhas, expressões e características próprias.</p><p>Formato do rosto, olhos, sobrancelhas, lábios, proporções e personalidade são considerados para criar uma maquiagem que valorize sua imagem de maneira intencional.</p><p>O objetivo não é transformar quem você é. É evidenciar o que já existe em você. Antes de pensar em tendências, penso em você.</p><p>Uma maquiagem pode ser bonita. Mas quando é pensada para você, ela se torna sua.</p></Reveal></div><div className="col-lg-5 offset-lg-1"><Reveal className="framed-image"><Image src={withBasePath(media.owner[1].src)} alt={media.owner[1].alt} width={1365} height={2048} sizes="(max-width: 991px) 88vw, 36vw" /></Reveal></div></div></div></section>
  <section id="precious-beauty" className="section-space dark-section method-section"><div className="container"><Reveal><p className="eyebrow gold">05 · A ASSINATURA</p><div className="row"><div className="col-lg-8"><h2>Precious<br/><em>Beauty</em></h2><p className="lead-serif">A beleza que existe em você é preciosa.</p></div><div className="col-lg-4"><p>Minha assinatura de maquiagem une técnica, personalização e propósito. Cada produção parte dos seus traços, identidade, ocasião e da imagem que deseja transmitir.</p><p><strong>É sobre revelar, não substituir.</strong></p></div></div><div className="manifesto-grid">{['Realçar seus olhos','Valorizar seus contornos','Evidenciar seus melhores traços','Harmonizar sua imagem','Respeitar sua identidade','Despertar sua confiança'].map((text, i)=><span key={text}><b>{String(i+1).padStart(2,'0')}</b>{text}</span>)}</div><blockquote className="quote-large text-center">“Você não precisa se tornar outra para ser extraordinária, só precisa descobrir o que já existe em você.”</blockquote></Reveal></div></section></>
}

export function Differentials() {
  return <section className="section-space paper-section"><div className="container"><div className="row mb-5"><div className="col-lg-6"><p className="eyebrow brown">06 · DIFERENCIAIS</p><h2>O que torna cada<br/>experiência <em>Precious?</em></h2></div><div className="col-lg-5 offset-lg-1"><p className="lead-serif">Excelência está na soma de técnica, olhar e cuidado.</p></div></div><div className="differential-list">{differentials.map((item,i)=><Reveal key={item.title} delay={i*.04}><article><span>{item.number}</span><h3>{item.title}</h3><p>{item.text}</p></article></Reveal>)}</div><p className="closing-rhythm">Técnica para realçar. <i>Olhar para perceber.</i> Cuidado para acolher. <i>Propósito para servir.</i></p></div></section>
}
