import Image from 'next/image'
import { Reveal } from '@/components/motion/Reveal'
import { media } from '@/data/media'
import { withBasePath } from '@/lib/paths'

export function Hero() {
  return <section id="inicio" className="hero-section dark-section"><div className="hero-ornament" aria-hidden="true" /><div className="container-fluid px-3 px-lg-5 h-100"><div className="row h-100 align-items-end align-items-lg-center">
    <div className="col-lg-6 order-2 order-lg-1 hero-copy"><Reveal><p className="eyebrow">ESPECIALISTA EM MAQUIAGEM</p><h1>Emily<br/><em>Bordignoni</em></h1><p className="hero-signature">Embelezamento com propósito.</p><p className="hero-lead">Uma experiência de beleza criada para valorizar seus traços, revelar sua identidade única e fortalecer a sua confiança.</p><div className="d-flex flex-column flex-sm-row gap-3"><a className="button button-light" href="#portfolio">Conheça meu trabalho</a><a className="button button-outline" href="#agendar">Agende seu atendimento</a></div></Reveal></div>
    <div className="col-lg-6 order-1 order-lg-2 hero-image-wrap"><div className="hero-image"><Image src={withBasePath(media.owner[7].src)} alt={media.owner[7].alt} fill priority sizes="(max-width: 991px) 100vw, 50vw" /></div><span className="image-caption">PRECIOUS BEAUTY · FERNANDÓPOLIS</span></div>
  </div></div><blockquote>“Tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor.” <cite>Colossenses 3:23</cite></blockquote></section>
}

export function AboutPurpose() {
  return <><section id="sobre" className="section-space paper-section"><div className="container"><div className="row g-5 align-items-center"><div className="col-lg-5"><Reveal className="about-collage"><Image className="about-main" src={withBasePath(media.owner[3].src)} alt={media.owner[3].alt} width={1365} height={2048} sizes="(max-width: 991px) 78vw, 34vw" /><Image className="about-detail" src={withBasePath(media.owner[2].src)} alt={media.owner[2].alt} width={1365} height={2048} sizes="28vw" /></Reveal></div><div className="col-lg-6 offset-lg-1"><Reveal><p className="eyebrow brown">02 · SOBRE MIM</p><h2>Quem é Emily<br/><em>Bordignoni</em></h2><p className="lead-serif">Especialista em maquiagem, apaixonada por revelar beleza com propósito.</p><p>Sou Emily Bordignoni, especialista em maquiagem, com especializações e certificações profissionais na área da beleza.</p><p>Ao longo dos anos, construí meu trabalho buscando mais do que técnica. Aprendi a observar detalhes, compreender traços e entender que uma maquiagem bem executada nasce da intenção por trás de cada decisão.</p><p>Meu trabalho é valorizar a imagem, os traços e a identidade de cada mulher, criando uma produção que faça sentido para quem ela é e para o momento que está vivendo.</p><p>Acredito que Deus me chamou para cuidar das filhas Dele. Cada atendimento é uma oportunidade de acolher, ouvir e fazer uma mulher se lembrar do seu próprio valor.</p><blockquote className="quote-large">“Eu nunca tinha me visto assim. Nem sabia que eu era tão bonita.”</blockquote><p>Embelezar, para mim, é também fazer uma mulher enxergar com mais carinho aquilo que Deus já colocou nela.</p></Reveal></div></div></div></section>
  <section id="proposito" className="section-space coffee-section"><div className="container"><div className="row"><div className="col-lg-5"><Reveal><p className="eyebrow gold">03 · MEU PROPÓSITO</p><h2>Beleza também<br/>é <em>identidade.</em></h2></Reveal></div><div className="col-lg-6 offset-lg-1"><Reveal><p className="lead-serif">Maquiagem vai muito além de aplicar produtos sobre um rosto. É uma obra de arte que envolve criatividade e estratégia.</p><p>Uma forma de valorizar a imagem, evidenciar os traços, comunicar identidade e despertar confiança. Cada mulher possui características que a tornam única.</p><p>Minha maquiagem é construída através do visagismo: formato do rosto, olhar, proporções, expressões, personalidade e ocasião fazem parte dessa construção.</p><p>Quero que você enxergue você mesma — valorizada, confiante e consciente da beleza que já possui. Que esse momento lembre que você é preciosa, criada com propósito e digna de ser cuidada.</p></Reveal></div></div></div></section></>
}
