import { bookingSteps, journey, preparation } from '@/data/content'
import { Reveal } from '@/components/motion/Reveal'

function Steps({ items }: { items: { number: string; title: string; text: string }[] }) { return <div className="steps-list">{items.map(item=><article key={item.number}><span>{item.number}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div> }

export function Practical() {
  return <><section id="atendimento" className="section-space paper-section"><div className="container"><div className="row"><div className="col-lg-4"><p className="eyebrow brown">10 · SUA JORNADA</p><h2>Como funciona<br/>o <em>atendimento</em></h2><p>Cada produção começa antes do primeiro pincel.</p></div><div className="col-lg-7 offset-lg-1"><Reveal><Steps items={journey}/></Reveal></div></div></div></section>
  <section className="section-space location-section"><div className="container"><p className="eyebrow brown">11 · ONDE ATENDO</p><h2>Você escolhe onde sua<br/><em>experiência acontece.</em></h2><div className="row g-4 mt-4"><div className="col-md-6"><article className="location-card"><span>01</span><h3>No meu espaço</h3><p>Em meu apartamento, em Fernandópolis — SP, um ambiente reservado para viver sua produção com tranquilidade, conforto e privacidade.</p><p>É onde acontecem Precious Beauty Experience e Precious Moments, mediante organização prévia.</p></article></div><div className="col-md-6"><article className="location-card dark"><span>02</span><h3>Atendimento a domicílio</h3><p>Para clientes que preferem não se deslocar, noivas, grupos, outras cidades e eventos que pedem maior comodidade.</p><p>Data, distância, quantidade de pessoas e logística são alinhadas previamente.</p></article></div></div></div></section>
  <section className="section-space preparation-section"><div className="container"><div className="row"><div className="col-lg-5"><p className="eyebrow gold">12 · PREPARAÇÃO</p><h2>Pequenos cuidados.<br/><em>Um resultado precioso.</em></h2><p>Para aproveitar o atendimento com tranquilidade, alguns cuidados fazem diferença.</p></div><div className="col-lg-6 offset-lg-1"><div className="prep-grid">{preparation.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></div><div className="bride-note"><p className="eyebrow gold">PARA AS NOIVAS</p><p>Reserve com antecedência para organizar horário, quantidade de pessoas, local, cabelo, cronograma, deslocamento e estrutura. No seu casamento, você não deveria estar preocupada com o relógio. <em>Você deveria estar vivendo o momento.</em></p></div></div></section>
  <section className="section-space booking-section"><div className="container"><div className="row"><div className="col-lg-5"><p className="eyebrow brown">13 · AGENDAMENTO</p><h2>Seu horário merece ser<br/><em>reservado com cuidado.</em></h2><p>Atendimentos são realizados exclusivamente com horário agendado. A taxa confirma e garante a reserva; não é um valor adicional ao serviço.</p><p>Datas de casamento, formaturas e eventos têm maior procura, especialmente em finais de semana. Para noivas e grupos, antecedência também permite organizar todo o cronograma.</p></div><div className="col-lg-6 offset-lg-1"><Steps items={bookingSteps}/></div></div></div></section></>
}
